--- !ditz.rubyforge.org,2008-03-06/project 
name: greenhouse
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: greenhouse
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.5"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-07-06 07:56:37.538934 Z
    - Travis Parker <travis.parker@gmail.com>
    - created
    - ""
labels: []

